name: Deploy Next.js App to Vercel with Pulumi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: latest

      - name: Configure Pulumi
        working-directory: .pulumi
        run: | 
          pulumi login --local
          PULUMI_CONFIG_PASSPHRASE="" pulumi config set vercel:team ${{ secrets.VERCEL_TEAM }}
          PULUMI_CONFIG_PASSPHRASE="" pulumi config set vercel:apiToken --secret ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy with Pulumi
        working-directory: .pulumi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: PULUMI_CONFIG_PASSPHRASE="" pulumi up --yes
